In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')
from sklearn import metrics

In [2]:
df=pd.read_csv('iris.csv')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.groupby(['species'])['species'].count()

species
setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
def converter(species):
    if species=='setosa':
        return 0
    elif species=='versicolor':
        return 1
    elif species=='virginica':
        return 2

In [7]:
df['new_species']=df['species'].apply(converter)

In [8]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,new_species
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.0,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.5,0.2,setosa,0
4,5.0,3.6,1.4,0.2,setosa,0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,2
146,6.3,2.5,5.0,1.9,virginica,2
147,6.5,3.0,5.2,2.0,virginica,2
148,6.2,3.4,5.4,2.3,virginica,2
149,5.9,3.0,5.1,1.8,virginica,2

In [9]:
df.drop(columns='species',axis=1,inplace=True)

In [10]:
df

     sepal_length  sepal_width  petal_length  petal_width  new_species
0             5.1          3.5           1.4          0.2            0
1             4.9          3.0           1.4          0.2            0
2             4.7          3.2           1.3          0.2            0
3             4.6          3.1           1.5          0.2            0
4             5.0          3.6           1.4          0.2            0
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3            2
146           6.3          2.5           5.0          1.9            2
147           6.5          3.0           5.2          2.0            2
148           6.2          3.4           5.4          2.3            2
149           5.9          3.0           5.1          1.8            2

[150 rows x 5 columns]

In [11]:
X=df.drop(labels='new_species',axis=1)
y=df[['new_species']]

In [12]:
len(X)

150

In [13]:
type(y)

pandas.core.frame.DataFrame

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=98)

In [15]:
logreg=LogisticRegression()

In [16]:
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
prediction=logreg.predict(X_test)

In [18]:
prediction

array([2, 1, 1, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 2,
       0, 0, 2, 0, 0, 1, 2, 0], dtype=int64)

In [19]:
y_train_prediction=logreg.predict(X_train)

In [20]:
y_train_prediction

array([2, 0, 2, 2, 1, 0, 2, 2, 2, 1, 2, 2, 1, 0, 2, 2, 0, 0, 1, 1, 0, 0,
       1, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0,
       0, 1, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 2,
       1, 1, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0,
       2, 0, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       2, 1, 2, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [21]:
newcolumns=X_test.join(y_test)

In [22]:
newcolumns

     sepal_length  sepal_width  petal_length  petal_width  new_species
70            5.9          3.2           4.8          1.8            1
96            5.7          2.9           4.2          1.3            1
94            5.6          2.7           4.2          1.3            1
52            6.9          3.1           4.9          1.5            1
46            5.1          3.8           1.6          0.2            0
78            6.0          2.9           4.5          1.5            1
72            6.3          2.5           4.9          1.5            1
97            6.2          2.9           4.3          1.3            1
102           7.1          3.0           5.9          2.1            2
14            5.8          4.0           1.2          0.2            0
77            6.7          3.0           5.0          1.7            1
53            5.5          2.3           4.0          1.3            1
90            5.5          2.6           4.4          1.2            1
41            4.5          2.3           1.3          0.3            0
56            6.3          3.3           4.7          1.6            1
140           6.7          3.1           5.6          2.4            2
111           6.4          2.7           5.3          1.9            2
75            6.6          3.0           4.4          1.4            1
87            6.3          2.3           4.4          1.3            1
76            6.8          2.8           4.8          1.4            1
98            5.1          2.5           3.0          1.1            1
116           6.5          3.0           5.5          1.8            2
18            5.7          3.8           1.7          0.3            0
5             5.4          3.9           1.7          0.4            0
128           6.4          2.8           5.6          2.1            2
10            5.4          3.7           1.5          0.2            0
29            4.7          3.2           1.6          0.2            0
82            5.8          2.7           3.9          1.2            1
122           7.7          2.8           6.7          2.0            2
8             4.4          2.9           1.4          0.2            0

In [23]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
101           5.8          2.7           5.1          1.9
11            4.8          3.4           1.6          0.2
109           7.2          3.6           6.1          2.5
139           6.9          3.1           5.4          2.1
58            6.6          2.9           4.6          1.3
..            ...          ...           ...          ...
38            4.4          3.0           1.3          0.2
71            6.1          2.8           4.0          1.3
65            6.7          3.1           4.4          1.4
91            6.1          3.0           4.6          1.4
42            4.4          3.2           1.3          0.2

[120 rows x 4 columns]

In [24]:
predicted_train=X_train.join(y_train)
predicted_train.head(22)

     sepal_length  sepal_width  petal_length  petal_width  new_species
101           5.8          2.7           5.1          1.9            2
11            4.8          3.4           1.6          0.2            0
109           7.2          3.6           6.1          2.5            2
139           6.9          3.1           5.4          2.1            2
58            6.6          2.9           4.6          1.3            1
49            5.0          3.3           1.4          0.2            0
133           6.3          2.8           5.1          1.5            2
137           6.4          3.1           5.5          1.8            2
127           6.1          3.0           4.9          1.8            2
68            6.2          2.2           4.5          1.5            1
135           7.7          3.0           6.1          2.3            2
117           7.7          3.8           6.7          2.2            2
51            6.4          3.2           4.5          1.5            1
22            4.6          3.6           1.0          0.2            0
100           6.3          3.3           6.0          2.5            2
126           6.2          2.8           4.8          1.8            2
28            5.2          3.4           1.4          0.2            0
31            5.4          3.4           1.5          0.4            0
62            6.0          2.2           4.0          1.0            1
80            5.5          2.4           3.8          1.1            1
1             4.9          3.0           1.4          0.2            0
15            5.7          4.4           1.5          0.4            0

In [25]:
predicted_train['prediction']=y_train_prediction

In [26]:
predicted_train.head(60)

,sepal_length,sepal_width,petal_length,petal_width,new_species,prediction
101,5.8,2.7,5.1,1.9,2,2
11,4.8,3.4,1.6,0.2,0,0
109,7.2,3.6,6.1,2.5,2,2
139,6.9,3.1,5.4,2.1,2,2
58,6.6,2.9,4.6,1.3,1,1
49,5.0,3.3,1.4,0.2,0,0
133,6.3,2.8,5.1,1.5,2,2
137,6.4,3.1,5.5,1.8,2,2
127,6.1,3.0,4.9,1.8,2,2
68,6.2,2.2,4.5,1.5,1,1
135,7.7,3.0,6.1,2.3,2,2
117,7.7,3.8,6.7,2.2,2,2
51,6.4,3.2,4.5,1.5,1,1
22,4.6,3.6,1.0,0.2,0,0
100,6.3,3.3,6.0,2.5,2,2
126,6.2,2.8,4.8,1.8,2,2
28,5.2,3.4,1.4,0.2,0,0
31,5.4,3.4,1.5,0.4,0,0
62,6.0,2.2,4.0,1.0,1,1
80,5.5,2.4,3.8,1.1,1,1
1,4.9,3.0,1.4,0.2,0,0
15,5.7,4.4,1.5,0.4,0,0
99,5.7,2.8,4.1,1.3,1,1
83,6.0,2.7,5.1,1.6,1,2
44,5.1,3.8,1.9,0.4,0,0
7,5.0,3.4,1.5,0.2,0,0
45,4.8,3.0,1.4,0.3,0,0
134,6.1,2.6,5.6,1.4,2,2
13,4.3,3.0,1.1,0.1,0,0
106,4.9,2.5,4.5,1.7,2,2
21,5.1,3.7,1.5,0.4,0,0
4,5.0,3.6,1.4,0.2,0,0
3,4.6,3.1,1.5,0.2,0,0
54,6.5,2.8,4.6,1.5,1,1
16,5.4,3.9,1.3,0.4,0,0
110,6.5,3.2,5.1,2.0,2,2
20,5.4,3.4,1.7,0.2,0,0
39,5.1,3.4,1.5,0.2,0,0
27,5.2,3.5,1.5,0.2,0,0
66,5.6,3.0,4.5,1.5,1,1
92,5.8,2.6,4.0,1.2,1,1
115,6.4,3.2,5.3,2.3,2,2
36,5.5,3.5,1.3,0.2,0,0
47,4.6,3.2,1.4,0.2,0,0
37,4.9,3.6,1.4,0.1,0,0
63,6.1,2.9,4.7,1.4,1,1
138,6.0,3.0,4.8,1.8,2,2
69,5.6,2.5,3.9,1.1,1,1
114,5.8,2.8,5.1,2.4,2,2
74,6.4,2.9,4.3,1.3,1,1
57,4.9,2.4,3.3,1.0,1,1
119,6.0,2.2,5.0,1.5,2,2
103,6.3,2.9,5.6,1.8,2,2
33,5.5,4.2,1.4,0.2,0,0
85,6.0,3.4,4.5,1.6,1,1
120,6.9,3.2,5.7,2.3,2,2
0,5.1,3.5,1.4,0.2,0,0
48,5.3,3.7,1.5,0.2,0,0
112,6.8,3.0,5.5,2.1,2,2
147,6.5,3.0,5.2,2.0,2,2

In [27]:
logreg.score(X_train,y_train)

0.9916666666666667

In [28]:
logreg.score(X_test,y_test)

0.9333333333333333

In [29]:
newcolumns['predicted_values']=prediction

In [30]:
newcolumns

,sepal_length,sepal_width,petal_length,petal_width,new_species,predicted_values
70,5.9,3.2,4.8,1.8,1,2
96,5.7,2.9,4.2,1.3,1,1
94,5.6,2.7,4.2,1.3,1,1
52,6.9,3.1,4.9,1.5,1,1
46,5.1,3.8,1.6,0.2,0,0
78,6.0,2.9,4.5,1.5,1,1
72,6.3,2.5,4.9,1.5,1,1
97,6.2,2.9,4.3,1.3,1,1
102,7.1,3.0,5.9,2.1,2,2
14,5.8,4.0,1.2,0.2,0,0
77,6.7,3.0,5.0,1.7,1,2
53,5.5,2.3,4.0,1.3,1,1
90,5.5,2.6,4.4,1.2,1,1
41,4.5,2.3,1.3,0.3,0,0
56,6.3,3.3,4.7,1.6,1,1
140,6.7,3.1,5.6,2.4,2,2
111,6.4,2.7,5.3,1.9,2,2
75,6.6,3.0,4.4,1.4,1,1
87,6.3,2.3,4.4,1.3,1,1
76,6.8,2.8,4.8,1.4,1,1
98,5.1,2.5,3.0,1.1,1,1
116,6.5,3.0,5.5,1.8,2,2
18,5.7,3.8,1.7,0.3,0,0
5,5.4,3.9,1.7,0.4,0,0
128,6.4,2.8,5.6,2.1,2,2
10,5.4,3.7,1.5,0.2,0,0
29,4.7,3.2,1.6,0.2,0,0
82,5.8,2.7,3.9,1.2,1,1
122,7.7,2.8,6.7,2.0,2,2
8,4.4,2.9,1.4,0.2,0,0

In [31]:
probabilities = logreg.predict_proba(X_test)

In [32]:
print(probabilities)

[[2.78176764e-03 3.60873199e-01 6.36345033e-01]
 [2.23712912e-02 8.84687951e-01 9.29407578e-02]
 [1.91401616e-02 8.80786066e-01 1.00073772e-01]
 [1.39771502e-03 5.86292516e-01 4.12309769e-01]
 [9.77733779e-01 2.22660942e-02 1.26860912e-07]
 [7.22948569e-03 7.30596392e-01 2.62174122e-01]
 [9.77673817e-04 5.00870140e-01 4.98152187e-01]
 [1.17354542e-02 8.87623289e-01 1.00641257e-01]
 [3.73406777e-06 2.03098396e-02 9.79686426e-01]
 [9.86870868e-01 1.31291128e-02 1.93938840e-08]
 [7.21079306e-04 3.63619108e-01 6.35659813e-01]
 [2.09917872e-02 9.10024827e-01 6.89833862e-02]
 [1.15716792e-02 8.56391345e-01 1.32036976e-01]
 [9.60216386e-01 3.97833821e-02 2.31791677e-07]
 [4.69248755e-03 6.00109105e-01 3.95198408e-01]
 [9.58771104e-06 1.71556775e-02 9.82834735e-01]
 [1.01334577e-04 1.11858301e-01 8.88040364e-01]
 [7.18100731e-03 8.52873763e-01 1.39945230e-01]
 [4.09783525e-03 8.58044261e-01 1.37857904e-01]
 [1.57395529e-03 6.87172526e-01 3.11253518e-01]
 [2.79668344e-01 7.17799124e-01 2.53253151e-03]
 [7.47002348e-05 9.79336707e-02 9.01991629e-01]
 [9.54472351e-01 4.55272929e-02 3.55748537e-07]
 [9.68012951e-01 3.19866876e-02 3.61010267e-07]
 [1.67680460e-05 3.25738429e-02 9.67409389e-01]
 [9.74244984e-01 2.57549131e-02 1.03091133e-07]
 [9.68089126e-01 3.19106356e-02 2.38705592e-07]
 [3.36633618e-02 9.32371732e-01 3.39649064e-02]
 [5.86874513e-08 4.01141615e-03 9.95988525e-01]
 [9.77249426e-01 2.27504544e-02 1.19811118e-07]]

In [33]:
probabilities_2 = probabilities[:,2]
probabilities_1 = probabilities[:,1]
probabilities_0 = probabilities[:,0]

In [34]:
probabilities_2

array([6.36345033e-01, 9.29407578e-02, 1.00073772e-01, 4.12309769e-01,
       1.26860912e-07, 2.62174122e-01, 4.98152187e-01, 1.00641257e-01,
       9.79686426e-01, 1.93938840e-08, 6.35659813e-01, 6.89833862e-02,
       1.32036976e-01, 2.31791677e-07, 3.95198408e-01, 9.82834735e-01,
       8.88040364e-01, 1.39945230e-01, 1.37857904e-01, 3.11253518e-01,
       2.53253151e-03, 9.01991629e-01, 3.55748537e-07, 3.61010267e-07,
       9.67409389e-01, 1.03091133e-07, 2.38705592e-07, 3.39649064e-02,
       9.95988525e-01, 1.19811118e-07])

In [35]:
test_predictions = X_test.copy()

In [36]:
test_predictions['actual'] = y_test

In [37]:
test_predictions['predicted'] = prediction

In [38]:
alpha=np.round(probabilities_2,4)

In [39]:
test_predictions['probability'] = alpha

In [40]:
#test_predictions.drop(columns='probability_1',axis=1,inplace=True)

KeyError: "['probability_1'] not found in axis"

In [41]:
test_predictions

,sepal_length,sepal_width,petal_length,petal_width,actual,predicted,probability
70,5.9,3.2,4.8,1.8,1,2,0.6363
96,5.7,2.9,4.2,1.3,1,1,0.0929
94,5.6,2.7,4.2,1.3,1,1,0.1001
52,6.9,3.1,4.9,1.5,1,1,0.4123
46,5.1,3.8,1.6,0.2,0,0,0.0000
78,6.0,2.9,4.5,1.5,1,1,0.2622
72,6.3,2.5,4.9,1.5,1,1,0.4982
97,6.2,2.9,4.3,1.3,1,1,0.1006
102,7.1,3.0,5.9,2.1,2,2,0.9797
14,5.8,4.0,1.2,0.2,0,0,0.0000
77,6.7,3.0,5.0,1.7,1,2,0.6357
53,5.5,2.3,4.0,1.3,1,1,0.0690
90,5.5,2.6,4.4,1.2,1,1,0.1320
41,4.5,2.3,1.3,0.3,0,0,0.0000
56,6.3,3.3,4.7,1.6,1,1,0.3952
140,6.7,3.1,5.6,2.4,2,2,0.9828
111,6.4,2.7,5.3,1.9,2,2,0.8880
75,6.6,3.0,4.4,1.4,1,1,0.1399
87,6.3,2.3,4.4,1.3,1,1,0.1379
76,6.8,2.8,4.8,1.4,1,1,0.3113
98,5.1,2.5,3.0,1.1,1,1,0.0025
116,6.5,3.0,5.5,1.8,2,2,0.9020
18,5.7,3.8,1.7,0.3,0,0,0.0000
5,5.4,3.9,1.7,0.4,0,0,0.0000
128,6.4,2.8,5.6,2.1,2,2,0.9674
10,5.4,3.7,1.5,0.2,0,0,0.0000
29,4.7,3.2,1.6,0.2,0,0,0.0000
82,5.8,2.7,3.9,1.2,1,1,0.0340
122,7.7,2.8,6.7,2.0,2,2,0.9960
8,4.4,2.9,1.4,0.2,0,0,0.0000

In [42]:
from sklearn.metrics import accuracy_score
print('Accuracy score for test data is:', accuracy_score(y_test,prediction))

Accuracy score for test data is: 0.9333333333333333

In [43]:
from sklearn.metrics import confusion_matrix

confusion_matrix = pd.DataFrame(confusion_matrix(y_test, prediction))

print(confusion_matrix)

   0   1  2
0  8   0  0
1  0  14  2
2  0   0  6

In [44]:
confusion_matrix.index = ['Actual setosa','Actual versicolor','Actual virginica']
confusion_matrix.columns = ['Predicted setosa','Predicted versicolor','Predicted virginica']
print(confusion_matrix)

                   Predicted setosa  Predicted versicolor  Predicted virginica
Actual setosa                     8                     0                    0
Actual versicolor                 0                    14                    2
Actual virginica                  0                     0                    6